apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:qRQn6eG35GcIdP/pfiV69X0GRLVtVLt5lyS9nSaNKX0OFinhPmC9d/VS9TYTRvOwU/JAnC3cjQcrZ1bfdQ9VbVRKOY8Ya+VlgeXmk5A7c43N3nJ0aOk+rZK/1U66v18sgk+B6y+3RdKWluT6Mv3mlnSeufAKaYuy3QUs4zAOTa+/NmHBjxeFyA/fNLdhOtYbSXrjKejkWnw6MVyMJE1I+UjRLPZV9tGkv1dNatS0cNOvSkezsh67o+zaLtYfx968Gg62y+gSbJZmM+b2bVRP68Dcxyc6QoGJNYs4wmZa27gsNuPvY7cURYeeTPQ=,iv:Ri+Qk+c6z/kvYmwbY170hycmwDSgkd0iPawW6wTQVSw=,tag:C/PYG0HGAR6pEq7ci+gtdw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age19xqs7kfl0h4gpheaurgpxjtadhfe6fdxxdprcl4tj9arrd5695wqjkpr4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZU2p2TGQzOTlRbGFmV0s2
            U281V0pWQ0w4a2I5dkozMnVlVFRNeVZTaEFZCnZqb2hzQmFCRDNUbjVONldTWGV1
            TTBhdk9WUlZkdFZRRXlmL0gyRkdBbG8KLS0tIE5rakp5WHRSSE1WM0o5Rzc5bDNY
            M1BHWE8vQm1aZ1FLdDlySmJWU3ZRWTAKvF80y9WXFG2lhEdWdVUuKilG/n0ew/98
            alrXv6MUz+aJza5feoxUxEgjO79BvXg4RNZthwfrq/9T6kGVPAPQ1Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-21T10:58:53Z"
    mac: ENC[AES256_GCM,data:Rac3dzfKIKofRXe8Nt5uYvk85UQIgGT4IzvLxAFsWmSDlY1lOk2lvpT7u0figtL6IiXsnrpAe9Ma6BfpSHIjC/MdlSBrpIsxx83gPe+8OHJbLXJoAhmdyOHRsp9P29AGk7pZg6nSCy/88vu0haDtrdDHc65hzO81ApUjM/5xyjY=,iv:sOFYL526mcjLze+d2oSFhUBeCT9+C6zSqjlPwr393TA=,tag:ZMjDy2WLoc9PyiGhnrHjQw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
