apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controllers
  namespace: flux-system
spec:
  interval: 1m0s
  retryInterval: 1m
  timeout: 5m
  path: ./monitoring/controllers/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
   provider: sops
   secretRef:
     name: sops-age
  dependsOn:
    - name: monitoring-configs
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
 name: monitoring-configs
 namespace: flux-system
spec:
 interval: 1m0s
 retryInterval: 1m
 timeout: 5m
 sourceRef:
   kind: GitRepository
   name: flux-system
 path: ./monitoring/configs/staging
 prune: true
 decryption:
   provider: sops
   secretRef:
     name: sops-age
